apiVersion: batch/v1
kind: Job
metadata:
  name: rfm-loader-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loader
        image: rfm-loader:latest
        imagePullPolicy: Never
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: rfm-app-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: rfm-app-config
              key: MONGO_PORT
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
